version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  node: circleci/node@5.0.0
jobs:
  build_test:
    docker:
      - image: shaharboroc/multi-client
        auth:
          username: shaharboroc
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: Run Tests
          command: |
            npm run test


workflows:
  build_test_deploy:
    jobs:
      - build_test